[package]
name = "oort_proto"
version = "0.79.1"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.37", features = ["serde"] }
