[package]
name = "oort_version_control"
version = "0.64.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.30"
flate2 = "1.0.27"
idb = "0.4.1"
js-sys = "0.3.64"
log = "0.4.20"
serde = { version = "1.0.188", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
sha2 = "0.10.7"
thiserror = "1.0.48"
wasm-bindgen = "0.2.87"
