[package]
name = "oort_backend_service"
version = "0.54.2"
publish = false
edition = "2021"

[dependencies]
oort_envelope = { path = "../../shared/envelope" }
oort_code_encryption = { path = "../../shared/code_encryption" }
oort_proto = { path = "../../shared/proto" }
anyhow = "1.0"
chrono = "0.4.26"
firestore = "0.32.2"
gcloud-sdk = "0.20.4"
log = "0.4.19"
rand = "0.8.5"
regex = "1.9.1"
reqwest = { version = "0.11.18", default-features=false, features = ["json", "rustls-tls"] }
serde_json = "1.0.104"
stackdriver_logger = "0.8.2"
tokio = { version = "1.29", features = ["macros", "rt-multi-thread", "process"] }
axum = "0.6.19"
tower-http = { version = "0.4.3", features = ["cors", "trace"] }
http = "0.2.9"
tracing-subscriber = "0.3.17"
bytes = "1.4.0"
