[package]
name = "oort_builtin_ai"
version = "0.79.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oort_api = { path = "../../shared/api" }
