[package]
name = "oort_simulation_worker"
version = "0.61.0"
edition = "2021"
publish = false

[dependencies]
oort_simulator = { path = "../../shared/simulator", features = ["js"], default-features = false }
yew-agent = "0.2.0"
serde = "1.0.188"
