[package]
name = "oort_code_encryption"
version = "0.54.1"
publish = false
edition = "2021"

[dependencies]
aes-gcm = { version = "0.10.2", features = ["std"] }
anyhow = "1.0.72"
base64 = "0.21.2"
bincode = "1.3.3"
flate2 = "1.0.26"
rand = "0.8.5"
serde = { version = "1.0.180", features = ["derive"] }
sha2 = "0.10.7"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "benchmark"
harness = false
