[package]
name = "oort-bundler"
version = "0.79.0"
edition = "2021"

[dependencies]
oort_multifile = { path = "../shared/multifile" }
notify = "6.1.1"
env_logger = "0.10.1"
clap = { version = "4.4.8", features = ["derive"] }
anyhow = "1.0.75"
