[package]
name = "oort_version"
version = "0.68.1"
publish = false
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
built = { version = "0.7", features = ["git2", "chrono", "semver"] }
