[package]
name = "oort_tools"
version = "0.78.0"
publish = false
edition = "2021"
resolver = "2"

[dependencies]
oort_proto = { path = "../shared/proto" }
oort_simulator = { path = "../shared/simulator", features = ["precompile"] }
oort_compiler = { path = "../shared/compiler" }
oort_api = { path = "../shared/api" }
firestore = "0.37.2"
gcloud-sdk = "0.21.2"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.34", features = ["full"] }
log = "0.4.20"
env_logger = "0.10.1"
reqwest = { version = "0.11.22", default-features = false, features = ["json", "blocking", "rustls-tls"] }
rayon = "1.8.0"
serde_json = "1.0"
chrono = "0.4.31"
clap = { version = "4.4.8", features = ["derive"] }
skillratings = "0.26.0"
itertools = "0.11.0"
comfy-table = "7.1.0"
petname = "1.1.3"
rand_chacha = "0.3.1"
rand_seeder = "0.2.3"
rusqlite = { version = "0.30.0", features = ["bundled"] }
anyhow = "1.0.75"
shell-words = "1.1.0"
toml = "0.8.8"
indicatif = { version = "0.17.7", features = ["tokio"] }
once_cell = "1.18.0"
regex = "1.10.2"
rand = "0.8.5"
metaheuristics-nature = { version = "9.2.3", features = ["clap", "rayon"] }
tempdir = "0.3.7"
glob = "0.3.1"
tar = "0.4.40"
libflate = "2.0.0"
tokio-retry = "0.3.0"
goose = "0.17.2"
nalgebra = "0.32.3"
futures = "0.3.29"
indicatif-log-bridge = "0.2.2"
